name: LibreSSL

on:
  push: {}

concurrency:
  group: libressl-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  libressl:
    name: LibreSSL
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3

      - name: Restore/backup ccache
        uses: actions/cache@v3
        with:
          path: ccache
          key: ccache/libressl

      - name: Update package cache
        run: sudo apt-get update

      - name: Install build dependencies
        run: >
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y
          --no-install-{recommends,suggests}
          bison ccache cmake flex g++ lib{boost-all,ssl}-dev ninja-build tzdata

      - name: Build
        run: sudo .github/workflows/libressl.bash
